#ifndef __SDK_WAFFLE_COMPONENT_H_
#define __SDK_WAFFLE_COMPONENT_H_

#ifdef WAFFLE_COMPONENT_BUILD
#define WAFFLE_COMPONENT_FUNCTION LIBRARY_EXPORT
#else
#define WAFFLE_COMPONENT_FUNCTION
#endif

WAFFLE_COMPONENT_FUNCTION SIZE_T WINAPI ComponentInit(
    _In_    LPWAFFLE_PROCESS_SETTING lpstProcessSetting
    );

typedef SIZE_T(WINAPI *LPCOMPONENTINIT)(
    _In_    LPWAFFLE_PROCESS_SETTING lpstProcessSetting
    );

#endif /* __SDK_WAFFLE_COMPONENT_H_ */